### Super Smash Bros. Ultimate – Game Character and Game Listing

A couple of weeks ago “Pro Gamer” Dude was gifted with Super Smash Bros. Ultimate for his Nintendo Switch Lite.

We both agree that it is one of the best games on the Switch. From my side I love the roster of fighters, a question we always ask is in which game did the fighter originally appear in?

That is why I put together the below chart to keep as a reference to answer that question.

|                                                                                                        |                    Fighter Name                   |                     First Game Appearance                     |
|:------------------------------------------------------------------------------------------------------:|:-------------------------------------------------:|:-------------------------------------------------------------:|
| ![Mario](/assets/images/prj_smash/001_Mario.jpg)                                                       | Mario                                             | Donkey Kong                                                   |
| ![Donkey Kong](/assets/images/prj_smash/002_Donkey_Kong.jpg)                                           | Donkey Kong                                       | Donkey Kong Country                                           |
| ![Link](/assets/images/prj_smash/003_Link.jpg)                                                         | Link                                              | The Legend of Zelda                                           |
| ![Samus](/assets/images/prj_smash/004_Samus.jpg)                                                       | Samus                                             | Metroid                                                       |
| ![Dark Samus](/assets/images/prj_smash/004e_Dark_Samus.jpg)                                            | Dark Samus                                        | Metroid Prime (Echo Fighter)                                  |
| ![Yoshi](/assets/images/prj_smash/005_Yoshi.jpg)                                                       | Yoshi                                             | Super Mario World                                             |
| ![Kirby](/assets/images/prj_smash/006_Kirby.jpg)                                                       | Kirby                                             | Kirby’s Dream Land                                            |
| ![Fox](/assets/images/prj_smash/007_Fox_McCloud.jpg)                                                   | Fox                                               | Star Fox                                                      |
| ![Pikachu](/assets/images/prj_smash/008_Pikachu.jpg)                                                   | Pikachu                                           | Pokémon Red and Blue                                          |
| ![Luigi](/assets/images/prj_smash/009_Luigi.jpg)                                                       | Luigi                                             | Mario Bros.                                                   |
| ![Ness](/assets/images/prj_smash/010_Ness.jpg)                                                         | Ness                                              | EarthBound                                                    |
| ![Captain Falcon](/assets/images/prj_smash/011_Captain_Falcon.jpg)                                     | Captain Falcon                                    | F-Zero                                                        |
| ![Jigglypuff](/assets/images/prj_smash/012_Jigglypuff.jpg)                                             | Jigglypuff                                        | Pokémon Red and Blue                                          |
| ![Princess Peach](/assets/images/prj_smash/013_Peach.jpg)                                              | Princess Peach                                    | Super Mario Bros.                                             |
| ![Princess Daisy](/assets/images/prj_smash/013e_Daisy.jpg)                                             | Princess Daisy                                    | Super Mario Land (Echo Fighter)                               |
| ![Bowser](/assets/images/prj_smash/014_Bowser.jpg)                                                     | Bowser                                            | Mario Bros.                                                   |
| ![Ice Climbers](/assets/images/prj_smash/015_Ice_Climbers.jpg)                                         | Ice Climbers                                      | Ice Climber                                                   |
| ![Sheik](/assets/images/prj_smash/016_Sheik.jpg)                                                       | Sheik                                             | The Lengend of Zelda: Ocarina of Time                         |
| ![Princess Zelda](/assets/images/prj_smash/017_Princess_Zelda.jpg)                                     | Princess Zelda                                    | The Lengend of Zelda                                          |
| ![Dr. Mario](/assets/images/prj_smash/018_Dr_Mario.jpg)                                                | Dr. Mario                                         | Dr. Mario                                                     |
| ![Pichu](/assets/images/prj_smash/019_Pichu.jpg)                                                       | Pichu                                             | Pokémon Gold and Silver                                       |
| ![Falco](/assets/images/prj_smash/020_Falco_Lombardi.jpg)                                              | Falco                                             | Star Fox                                                      |
| ![Martha](/assets/images/prj_smash/021_Marth.jpg)                                                      | Martha                                            | Fire Emblem: Shadow Dragon and Blade of Light                 |
| ![Lucina](/assets/images/prj_smash/021e_Lucina.jpg)                                                    | Lucina                                            | Fire Emblem Fates (Echo Fighter)                              |
| ![Young Link](/assets/images/prj_smash/022_Young_Link.jpg)                                             | Young Link                                        | The Legend of Zelda                                           |
| ![Ganondorf](/assets/images/prj_smash/023_Ganondorf.jpg)                                               | Ganondorf                                         | The Legend of Zelda                                           |
| ![Mewtwo](/assets/images/prj_smash/024_Mewtwo.jpg)                                                     | Mewtwo                                            | Pokémon Red and Blue                                          |
| ![Roy](/assets/images/prj_smash/025_Roy.jpg)                                                           | Roy                                               | Fire Emblem: The Binding Blade                                |
| ![Chrom](/assets/images/prj_smash/025e_Chrom.jpg)                                                      | Chrom                                             | Fire Emblem Fates (Echo Fighter)                              |
| ![Mr. Game & Watch](/assets/images/prj_smash/026_Mr_Game_&_Watch.jpg)                                  | Mr. Game & Watch                                  | Ball                                                          |
| ![Meta Knight](/assets/images/prj_smash/027_Metaknight.jpg)                                            | Meta Knight                                       | Kirby’s Adventure                                             |
| ![Pit](/assets/images/prj_smash/028_Pit.jpg)                                                           | Pit                                               | Kid Icarus                                                    |
| ![Dark Pit](/assets/images/prj_smash/028e_Dark_Pit.jpg)                                                | Dark Pit                                          | Kid Icarus: Uprising (Echo Fighter)                           |
| ![Zero Suit Samus](/assets/images/prj_smash/029_Zero_Suit_Samus.jpg)                                   | Zero Suit Samus                                   | Metroid: Zero Mission                                         |
| ![Wario](/assets/images/prj_smash/030_Wario.jpg)                                                       | Wario                                             | Super Mario Land 2                                            |
| ![Solid Snake](/assets/images/prj_smash/031_Solid_Snake.jpg)                                           | Solid Snake                                       | Metal Gear                                                    |
| ![Ike](/assets/images/prj_smash/032_Ike.jpg)                                                           | Ike                                               | Fire Emblem: Path of Radiance                                 |
| ![Pokémon Trainer (Squirtle, Ivysaur and Charizard)](/assets/images/prj_smash/033_Pokemon_Trainer.jpg) | Pokémon Trainer (Squirtle, Ivysaur and Charizard) | Pokémon Red and Blue                                          |
| ![Diddy Kong](/assets/images/prj_smash/036_Diddy_Kong.jpg)                                             | Diddy Kong                                        | Donkey Kong Country                                           |
| ![Lucas](/assets/images/prj_smash/037_Lucas.jpg)                                                       | Lucas                                             | Mother 3                                                      |
| ![Sonic](/assets/images/prj_smash/038_Sonic.jpg)                                                       | Sonic                                             | Sonic the Hedgehog                                            |
| ![King Dedede](/assets/images/prj_smash/039_King_Dedede.jpg)                                           | King Dedede                                       | Kirby’s Dream Land                                            |
| ![Olimar](/assets/images/prj_smash/040_Olimar.jpg)                                                     | Olimar                                            | Pikmin                                                        |
| ![Lucario](/assets/images/prj_smash/041_Lucario.jpg)                                                   | Lucario                                           | Pokémon Mystery Dungeon: Blue Rescue Team and Red Rescue Team |
| ![R.O.B. (Robotic Operating Buddy)](/assets/images/prj_smash/042_ROB.jpg)                              | R.O.B. (Robotic Operating Buddy)                  | Stack-Up                                                      |
| ![Toon Link](/assets/images/prj_smash/043_Toon_Link.jpg)                                               | Toon Link                                         | The Legend of Zelda: The Wind Walker                          |
| ![Wolf](/assets/images/prj_smash/044_Wolf.jpg)                                                         | Wolf                                              | Star Fox 64                                                   |
| ![Villager](/assets/images/prj_smash/045_Villager.jpg)                                                 | Villager                                          | Animal Crossing                                               |
| ![Mega Man](/assets/images/prj_smash/046_Mega_Man.jpg)                                                 | Mega Man                                          | Mega Man                                                      |
| ![Wii Fit Trainer](/assets/images/prj_smash/047_Wii_Fit_Trainer.jpg)                                   | Wii Fit Trainer                                   | Wii Fit                                                       |
| ![Rosalina & Luma](/assets/images/prj_smash/048_Rosalin_Luma.jpg)                                      | Rosalina & Luma                                   | Super Mario Galaxy                                            |
| ![Little Mac](/assets/images/prj_smash/049_Little_Mac.jpg)                                             | Little Mac                                        | Mike Tyson’s Punch-Out!!                                      |
| ![Greninja](/assets/images/prj_smash/050_Greninja.jpg)                                                 | Greninja                                          | Pokémon X and Y                                               |
| ![Mii Fighter (Brawler, Swordfighter and Gunner)](/assets/images/prj_smash/051_Mii_Fighter.jpg)        | Mii Fighter (Brawler, Swordfighter and Gunner)    | Mii Channel / Wii Sports                                      |
| ![Palutena](/assets/images/prj_smash/054_Palutena.jpg)                                                 | Palutena                                          | Kid Icarus                                                    |
| ![Pac-Man](/assets/images/prj_smash/055_PAC-MAN.jpg)                                                   | Pac-Man                                           | Pac-Man                                                       |
| ![Robin](/assets/images/prj_smash/056_Robin.jpg)                                                       | Robin                                             | Fire Emblem: Awakening                                        |
| ![Shulk](/assets/images/prj_smash/057_Shulk.jpg)                                                       | Shulk                                             | Xenoblade Chronicles                                          |
| ![Bowser Jr.](/assets/images/prj_smash/058_Bowser_Jr.jpg)                                              | Bowser Jr.                                        | Super Mario Sunshine                                          |
| ![Duck Hunt Duo](/assets/images/prj_smash/059_Duck_Hunt_Duo.jpg)                                       | Duck Hunt Duo                                     | Duck Hunt                                                     |
| ![Ryu](/assets/images/prj_smash/060_Ryu.jpg)                                                           | Ryu                                               | Street Fighter                                                |
| ![Ken](/assets/images/prj_smash/060e_Ken.jpg)                                                          | Ken                                               | Street Fighter (Echo Fighter)                                 |
| ![Cloud](/assets/images/prj_smash/061_Cloud.jpg)                                                       | Cloud                                             | Final Fantasy VII                                             |
| ![Corrin](/assets/images/prj_smash/062_Corrin.jpg)                                                     | Corrin                                            | Fire Emblem Fates                                             |
| ![Bayonetta](/assets/images/prj_smash/063_Bayonetta.jpg)                                               | Bayonetta                                         | Bayonetta                                                     |
| ![Inkling](/assets/images/prj_smash/064_Inkling.jpg)                                                   | Inkling                                           | Splatoon                                                      |
| ![Ridley](/assets/images/prj_smash/065_Ridely.jpg)                                                     | Ridley                                            | Metroid                                                       |
| ![Simon Belmont](/assets/images/prj_smash/066_Simon_Belmont.jpg)                                       | Simon Belmont                                     | Castlevania                                                   |
| ![Richter Belmont](/assets/images/prj_smash/066e_Simon_Belmont.jpg)                                    | Richter Belmont                                   | Castlevania: Rondo of Blood (Echo Fighter)                    |
| ![King K. Rool](/assets/images/prj_smash/067_King_K_Rool.jpg)                                          | King K. Rool                                      | Donkey Kong Country                                           |
| ![Isabelle](/assets/images/prj_smash/068_Isabelle.jpg)                                                 | Isabelle                                          | Animal Crossing: New Leaf                                     |
| ![Incineroar](/assets/images/prj_smash/069_Incineroar.jpg)                                             | Incineroar                                        | Pokémon Sun and Moon                                          |
| ![Piranha Plant (DLC)](/assets/images/prj_smash/070_Piranha_Plant.jpg)                                 | Piranha Plant (DLC)                               | Super Mario Bros.                                             |
| ![Joker (DLC)](/assets/images/prj_smash/071_Joker.jpg)                                                 | Joker (DLC)                                       | Persona 5                                                     |
| ![Hero (DLC)](/assets/images/prj_smash/072_Hero.jpg)                                                   | Hero (DLC)                                        | Dragon Quest                                                  |
| ![Banjo & Kazooie (DLC)](/assets/images/prj_smash/073_Banjo_Kazooie.jpg)                               | Banjo & Kazooie (DLC)                             | Banjo-Kazooie                                                 |
| ![Terry (DLC)](/assets/images/prj_smash/074_Terry.jpg)                                                 | Terry (DLC)                                       | Fatal Fury                                                    |
| ![Byleth (DLC)](/assets/images/prj_smash/075_Byleth.jpg)                                               | Byleth (DLC)                                      | Fire Emblem Heros / Fire Emblem: Three Houses                 |
| ![Min Min (DLC)](/assets/images/prj_smash/076_Min_Min.jpg)                                             | Min Min (DLC)                                     | ARMS                                                          |
| ![Steve / Alex (DLC)](/assets/images/prj_smash/077_Steve_Alex.jpg)                                     | Steve / Alex (DLC)                                | Minecraft                                                     |
| ![Sephiroth (DLC)](/assets/images/prj_smash/078_Sephiroth.jpg)                                         | Sephiroth (DLC)                                   | Final Fantasy VII                                             |
| ![Pyra (DLC)](/assets/images/prj_smash/079_Pyra.jpg)                                                   | Pyra (DLC)                                        | Xenoblade Chronicles 2                                        |
| ![Mythra (DLC)](/assets/images/prj_smash/080_Mythra.jpg)                                               | Mythra (DLC)                                      | Xenoblade Chronicles 2                                        |
| ![Kazuya (DLC)](/assets/images/prj_smash/081_Kazuya.jpg)                                               | Kazuya (DLC)                                      | Tekken                                                        |
| ![Sora (DLC)](/assets/images/prj_smash/082_Sora.jpg)                                                   | Sora (DLC)                                        | Kingdom Hearts                                                |
